apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: prd-base
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - name: jenkins-http
    port: 80
    targetPort: 8080
  - name: jenkins-jnlp
    port: 50000
    targetPort: 5000

 
